### ISSUE TITLE
Resin WebGL support. 

### ISSUE THREAD

**Issue by mrjonny2** [resin-os/resin-odroid#15]
Does the current iteration of the resin OS allow for support for WebGL in chrome or electron or chromium?

**Comment by Page-** [comment]
@agherzan ?

**Comment by agherzan** [comment]
@Page- @mrjonny2 I'm not aware of any testing on this. Maybe @shaunmulligan knows something more.

**Comment by shaunmulligan** [comment]
@mrjonny2 I haven't tested this on a resinOS device, but it looks like some guys have had success using the --eglfs flag for chromium on the Ordoid C1 here: http://forum.odroid.com/viewtopic.php?f=112&t=8267

**Comment by agherzan** [comment]
This issue was moved to resin-os/resinos#45
