### ISSUE TITLE
Avoid local.conf migrations by fixing the local.conf.sample

### ISSUE THREAD

**Issue by agherzan** [resin-os/resin-odroid#59]
Currently the builds carries migrations of the local.conf:

```
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
```

This means that the sample one we are using are outdated.

**Comment by floion** [comment]
Fixed by https://github.com/resin-os/resin-odroid/pull/63

**Comment by floion** [comment]
PR merged. Closing this issue
